#! /usr/local/bin/ansible-playbook

# - import_playbook: glusterfs-provision.yml

- hosts: gluster
  become: yes
  gather_facts: no
  any_errors_fatal: true

  vars_files:
    - vars.yaml

  tasks:
    - name: Check filesystem
      ansible.builtin.stat:
        path: "{{ gluster_dataset_path }}"
      register: uploaded

    - name: Upload dataset to GFS
      ansible.builtin.copy:
        src: "{{ dataset_folder }}/{{ dataset_filename }}"
        remote_src: yes
        dest: "{{ gluster_dataset_path }}"
      run_once: yes
      when: not uploaded.stat.exists
