#! /usr/local/bin/ansible-playbook

# - import_playbook: glusterfs-provision.yml

- hosts: gluster
  become: yes
  gather_facts: no
  any_errors_fatal: true

  vars_files:
    - vars.yaml

  tasks:
    - name: Upload dataset to GFS
      ansible.builtin.copy:
        src: "{{ dataset_path }}" 
        remote_src: yes 
        dest: "{{ gluster_data_dir }}"
      run_once: yes
      