version: '3'

volumes:
  vol_portainer:
  vol_gateway_certs:

networks:
  workbench:
    external: true
  net_traefik:
    external: true


services:
  traefik:
    image: pluribus/traefik:v2.6.1
    build:
      context: ./traefik
      dockerfile: Dockerfile
      args:
        TRAEFIK_BASE: "v2.6.1"
    restart: unless-stopped
    networks:
      - net_traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vol_gateway_certs:/certs
    security_opt:
      - no-new-privileges=true # https://docs.docker.com/engine/reference/run/#security-configuration      
    env_file:
      - ./env
    environment:
      - TRAEFIK_SWARM_MODE=true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
  
#----------------------------------------------------------------------------------
# monitor service
#----------------------------------------------------------------------------------
  agent:
    image: portainer/agent:2.12.1-alpine 
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_PORT: 40091
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - workbench
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
    env_file:
      - ./env

  # the following pointers are relevant for configuring portainer
  # https://documentation.portainer.io/archive/1.23.2/configuration/
  # https://stackoverflow.com/questions/42139605/how-do-you-manage-secret-values-with-docker-compose-v3-1
  # https://github.com/portainer/portainer/issues/1506
  # docker run --rm httpd:2.4-alpine htpasswd -nbB admin 'password' | cut -d ":" -f 2
  portainer:
    image: portainer/portainer-ce:2.11.1-alpine
    command: -H tcp://tasks.agent:40091 --tlsskipverify --admin-password="$$2y$$05$$RHexFs6Yw8763FQvtrv6dOw9z.TLdfp7myCBfDW6iu/iYipAqnM62"
    volumes:
      - vol_portainer:/data
    env_file:
      - ./env
    networks:
      - net_traefik
      - workbench
    ports:
      - 9090:9000
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.docker.network=net_traefik  # required when container connects to more than one network
        - traefik.http.services.to-portainer.loadbalancer.server.port=9000
        - traefik.http.routers.to-portainer.rule=Host(`portainer.pluribus.vcap.me`)
        # - traefik.http.routers.to-portainer.tls=true
        # - traefik.http.routers.to-portainer.entrypoints=websecure
        - traefik.http.routers.to-portainer.entrypoints=web
